from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, ForeignKey, String, Table, Text, CheckConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database import Base

# Allowed values for the clothing traits. The AI's answers should be mapped onto these.
CATEGORIES = ["top", "bottom", "dress", "outerwear", "shoes", "accessory"]
COLOURS = [
    "black", "white", "grey", "beige", "brown", "red", "orange",
    "yellow", "green", "blue", "navy", "purple", "pink", "multicolour",
]
PATTERNS = ["solid", "striped", "checked", "floral", "spotted", "graphic", "other"]
SEASONS = ["spring_summer", "autumn_winter"]


def _in_list(column: str, values: list[str]) -> str:
    return f"{column} IN ({', '.join(repr(v) for v in values)})"


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


# Join table: which clothing items belong to which saved outfit (many-to-many).
outfit_items = Table(
    "outfit_items",
    Base.metadata,
    Column("outfit_id", ForeignKey("outfits.id"), primary_key=True),
    Column("item_id", ForeignKey("clothing_items.id"), primary_key=True),
)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100))
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))  # bcrypt hash, never the real password
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    # Deleting a user also deletes their wardrobe and outfits.
    items: Mapped[list["ClothingItem"]] = relationship(back_populates="owner", cascade="all, delete-orphan")
    outfits: Mapped[list["Outfit"]] = relationship(back_populates="owner", cascade="all, delete-orphan")


class ClothingItem(Base):
    """One piece of clothing in a user's digital wardrobe."""
    __tablename__ = "clothing_items"
    __table_args__ = (
        CheckConstraint(_in_list("category", CATEGORIES), name="ck_item_category"),
        CheckConstraint(_in_list("colour", COLOURS), name="ck_item_colour"),
        CheckConstraint(_in_list("pattern", PATTERNS), name="ck_item_pattern"),
        CheckConstraint(_in_list("season", SEASONS), name="ck_item_season"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)

  
    # Images in Azure Blob Storage, only filenames saved
    image_filename: Mapped[str] = mapped_column(String(255))

    category: Mapped[str] = mapped_column(String(30))
    colour: Mapped[str] = mapped_column(String(30))
    pattern: Mapped[str] = mapped_column(String(30), default="solid")
    season: Mapped[str] = mapped_column(String(20))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    owner: Mapped["User"] = relationship(back_populates="items")
    outfits: Mapped[list["Outfit"]] = relationship(secondary=outfit_items, back_populates="items")


class Outfit(Base):
    """A saved look generated by the AI from the user's own wardrobe."""
    __tablename__ = "outfits"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    name: Mapped[str] = mapped_column(String(100))
    prompt: Mapped[str | None] = mapped_column(Text)        # what the user asked for, e.g. "job interview, rainy day"
    description: Mapped[str | None] = mapped_column(Text)   # the AI's explanation of the look
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    owner: Mapped["User"] = relationship(back_populates="outfits")
    items: Mapped[list["ClothingItem"]] = relationship(secondary=outfit_items, back_populates="outfits")
